language: ruby
rvm: 2.0.0
env:
  global:
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=travis@example.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=travis@example.com
    - secure: "cWwGicBmzR91ptlHWyN5xDTGWhVybSDpnK647gYq/hjKA0/qPJyyfxfjUYt4S3nftREaIUbLNO6IXJqFeuGySouPPOVZu9PO3Xx/Lh3YlSrc84xrzoDrEPGZU8w2rWWRGRjMhoJzTRjue5PmTVntQri99M3CxqKMtw9gf749Y1o="
before_script:
    - git clone --quiet https://github.com/soramugi/jr-passenger.git build
    - pushd build
    - git checkout -b gh-pages
    - popd
script:
    - bundle exec middleman build
after_success:
    - cd build
    - git add -A
    - git commit -m 'Update'
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/soramugi/jr-passenger.git gh-pages 2> /dev/null'
