language: ruby
rvm: 2.0.0
env:
  global:
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=travis@example.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=travis@example.com
    - secure: "cWwGicBmzR91ptlHWyN5xDTGWhVybSDpnK647gYq/hjKA0/qPJyyfxfjUYt4S3nftREaIUbLNO6IXJqFeuGySouPPOVZu9PO3Xx/Lh3YlSrc84xrzoDrEPGZU8w2rWWRGRjMhoJzTRjue5PmTVntQri99M3CxqKMtw9gf749Y1o="
script:
  - bundle exec middleman build
after_success:
  - cd build
  - git init
  - git add --all
  - git commit -m "Update from Travis CI"
  - 'git push --quiet https://$GH_TOKEN@github.com/soramugi/jr-passenger.git HEAD:gh-pages -f 2> /dev/null'
